import { CHILD_CARE_ICONS } from './childcare/childCareServicesAssets';
import { SENIOR_PERSONAL_CARE_ICONS } from './seniorpersonalcare/seniorPersonalCareAssets';
import { HOME_CLEANING_ICONS } from './homecleaning/homeCleaningServicesAssets';

export const CHILD_CARE_SERVICES = [
  {
    id: 'full-time-nannies',
    title: 'Full-time Nannies',
    description: 'Dedicated full-time care for your children with love and attention.',
    icon: CHILD_CARE_ICONS.fullTimeNannies,
    alt: 'Full-time Nannies',
    color: 'pink',
    detailTitle: 'What Full-time Nanny Care Includes',
    includes: [
      'Daily supervision and safety',
      'Feeding and healthy meals/snacks',
      'Bathing, dressing, and grooming',
      'Diaper and toilet support',
      'Routines, naps, and bedtime',
      'Reading, homework, and creative activities',
      'Developmental and social support',
      'School/activity transport and outings',
      'Child laundry, rooms, and items',
      'Health monitoring and basic first aid',
      'Parent updates and schedule coordination',
    ],
    notIncluded: [
      'Deep house cleaning',
      'Full family housekeeping',
      'Yard work',
      'Extensive cooking for all household members',
      'Unrelated personal errands',
    ],
  },
  {
    id: 'part-time-nannies',
    title: 'Part-time Nannies',
    description: "Flexible part-time care that fits your family's schedule.",
    icon: CHILD_CARE_ICONS.partTimeNannies,
    alt: 'Part-time Nannies',
    color: 'green',
    detailTitle: 'What Part-time Nanny Care Includes',
    includes: [
      'Scheduled supervision',
      'Meals and snacks',
      'Hygiene support',
      'Reading, play, arts, and homework',
      'School/daycare pickup and drop-off if needed',
      'Playdates and outings',
      'Child-area tidying and child laundry',
      'Nap and routine support',
      'Basic first aid',
      'Parent updates',
      'Optional child-related errands, evening, or holiday care by agreement',
    ],
    notIncluded: [
      'Deep cleaning',
      'Full housekeeping',
      'Extensive family cooking',
      'Yard maintenance',
      'Unrelated household-member care unless agreed',
    ],
  },
  {
    id: 'live-in-nannies',
    title: 'Live-in Nannies',
    description: 'Round-the-clock support and care right in your home.',
    icon: CHILD_CARE_ICONS.liveInNannies,
    alt: 'Live-in Nannies',
    color: 'purple',
    detailTitle: 'What Live-in Nanny Care Includes',
    includes: [
      'Full-time supervision',
      'Morning and bedtime care',
      'Meals and hygiene',
      'Educational and developmental support',
      'School/activity transport',
      'Child laundry, bedrooms, and play areas',
      'Health monitoring and basic first aid',
      'Daily parent updates',
      'Optional overnight support, parental-travel coverage, family meal prep, and light child-related housekeeping by agreement',
      'Family typically provides private room, bathroom access, meals during work periods, and utilities/accommodation',
    ],
  },
  {
    id: 'babysitters',
    title: 'Babysitters',
    description: 'Safe and engaging care for your children when you need it.',
    icon: CHILD_CARE_ICONS.babysitters,
    alt: 'Babysitters',
    color: 'orange',
    detailTitle: 'What Babysitting Includes',
    includes: [
      'Short-term supervision and safety',
      'Feeding and bottle feeding',
      'Diapers, toilet, and hygiene',
      'Games, reading, arts, and educational play',
      'Naps and bedtime',
      'Child-related cleanup',
      'Evening, weekend, overnight, holiday, or emergency care if agreed',
      'Parent updates',
    ],
    notIncluded: [
      'Deep cleaning',
      'Full household housekeeping',
      'Family laundry',
      'Extensive family meal prep',
      'Household maintenance and yard work',
    ],
  },
  {
    id: 'in-home-support',
    title: 'In-home Support',
    description: 'Reliable assistance with daily living activities at home.',
    icon: CHILD_CARE_ICONS.inHomeSupport,
    alt: 'In-home Support',
    color: 'blue',
    detailTitle: 'In-home Support Details',
    summaryOnly: true,
    summary:
      'Reliable assistance with daily living activities at home. Additional detailed service information is not yet available — please contact us to discuss your specific needs.',
  },
];

export const SENIOR_PERSONAL_CARE_SERVICES = [
  {
    id: 'companionship',
    title: 'Companionship',
    description: 'Meaningful companionship and emotional support.',
    icon: SENIOR_PERSONAL_CARE_ICONS.companionship,
    alt: 'Companionship',
    color: 'pink',
    detailTitle: 'What Companionship Includes',
    includes: [
      'Conversation and emotional support',
      'Games, reading, and hobbies',
      'Walks and outings',
      'Meal planning and grocery support',
      'Medication, hydration, and appointment reminders',
      'Transportation and escort',
      'Light housekeeping and laundry',
      'Wellness and home-safety observation',
      'Memory and recreational engagement',
      'Family updates and respite support',
    ],
    notIncluded: [
      'Medical treatments',
      'Injections',
      'Skilled nursing',
      'Physical therapy',
      'Heavy lifting or repairs',
    ],
  },
  {
    id: 'personal-care',
    title: 'Personal Care',
    description: 'Assistance with bathing, dressing, grooming & more.',
    icon: SENIOR_PERSONAL_CARE_ICONS.personalCare,
    alt: 'Personal Care',
    color: 'green',
    detailTitle: 'What Personal Care Includes',
    includes: [
      'Bathing and showering',
      'Dressing and grooming',
      'Hygiene and oral care',
      'Toileting and incontinence support',
      'Mobility, transfers, and walking',
      'Meal and feeding assistance',
      'Medication and hydration reminders',
      'Daily routines',
      'Companionship',
      'Light household help',
      'Transportation and errands',
      'Wellness observation and family coordination',
    ],
    notIncluded: [
      'Diagnosis or treatment',
      'Skilled nursing',
      'Injections',
      'Physical therapy',
      'Heavy housekeeping or repairs',
    ],
  },
  {
    id: 'transportation',
    title: 'Transportation',
    description: 'Safe transportation to appointments, school & more.',
    icon: SENIOR_PERSONAL_CARE_ICONS.transportation,
    alt: 'Transportation',
    color: 'purple',
    detailTitle: 'Transportation Support Includes',
    includes: [
      'Doctor, hospital, dental, therapy, and specialist trips',
      'Pharmacy visits',
      'Grocery, banking, post office, and shopping',
      'Social, community, and religious activities',
      'Door-to-door help',
      'Vehicle entry and exit assistance',
      'Walker, wheelchair, and belongings support',
      'Accompanied trips, waiting, and return home',
      'Selected specialized non-emergency transport',
      'Family updates',
    ],
    notIncluded: [
      'Ambulance or emergency treatment',
      'Licensed nursing during transit',
    ],
  },
  {
    id: 'meal-preparation',
    title: 'Meal Preparation',
    description: 'Nutritious meals prepared with care and attention.',
    icon: SENIOR_PERSONAL_CARE_ICONS.mealPreparation,
    alt: 'Meal Preparation',
    color: 'orange',
    detailTitle: 'Meal Preparation Support Includes',
    includes: [
      'Meal planning and customized menus',
      'Special-diet support',
      'Grocery lists, shopping, and storage',
      'Breakfast, lunch, dinner, snacks, and batch cooking',
      'Diabetic, low-sodium, heart-healthy, soft-food, allergy-aware, and cultural preferences',
      'Feeding assistance',
      'Kitchen cleanup',
      'Safe food handling',
      'Nutrition, hydration reminders, and family coordination',
    ],
    notIncluded: [
      'Clinical dietitian counseling',
      'Commercial or large-scale catering unless requested',
    ],
  },
  {
    id: 'light-housekeeping',
    title: 'Light Housekeeping',
    description: 'Keeping your home clean, organized & comfortable.',
    icon: SENIOR_PERSONAL_CARE_ICONS.lightHousekeeping,
    alt: 'Light Housekeeping',
    color: 'blue',
    detailTitle: 'Light Housekeeping Includes',
    includes: [
      'Dusting',
      'Vacuuming',
      'Sweeping and mopping',
      'Counters and tables',
      'Trash and recycling',
      'Kitchen dishes, counters, sinks, and appliances',
      'Laundry, linens, and bed making',
      'Bathroom upkeep',
      'Organization and decluttering',
      'Hazard reduction',
      'Mail, plants, grocery unpacking, and light pet care',
    ],
    notIncluded: [
      'Deep cleaning',
      'Carpet shampooing',
      'Exterior windows',
      'Heavy lifting',
      'Repairs or yard work',
    ],
  },
];

export const HOME_CLEANING_SERVICES = [
  {
    id: 'maid-services',
    title: 'Maid Services',
    description: 'General cleaning and household maintenance.',
    icon: HOME_CLEANING_ICONS.maidServices,
    alt: 'Maid Services',
    color: 'pink',
    detailTitle: 'Maid Services Include',
    includes: [
      'General housekeeping',
      'Kitchen, bathroom, and bedroom cleaning',
      'Laundry',
      'Home organization',
      'Deep cleaning',
      'Appliance cleaning',
      'Light household assistance',
      'Move-in/move-out cleaning',
      'Recurring options (daily, weekly, bi-weekly, monthly, one-time)',
    ],
    notIncluded: [
      'Heavy lifting',
      'Repairs',
      'Exterior windows',
      'Carpet installation or repair',
      'Landscaping or pest control',
    ],
  },
  {
    id: 'house-cleaning',
    title: 'House Cleaning',
    description: 'Thorough cleaning for a fresh and healthy home.',
    icon: HOME_CLEANING_ICONS.houseCleaning,
    alt: 'House Cleaning',
    color: 'green',
    detailTitle: 'House Cleaning Includes',
    includes: [
      'Living and common areas',
      'Kitchen',
      'Bathroom',
      'Bedrooms',
      'Laundry and linens',
      'Deep cleaning',
      'Closet, pantry, and storage organization',
      'Move-in/move-out',
      'Post-renovation',
      'Seasonal and spring cleaning',
      'Vacation-rental turnover',
    ],
    notIncluded: [
      'Exterior windows',
      'Carpet steam cleaning',
      'Furniture moving',
      'Yard work',
      'Pest control or repairs',
    ],
  },
  {
    id: 'carpet-cleaning',
    title: 'Carpet Cleaning',
    description: 'Deep carpet cleaning for a cleaner, healthier environment.',
    icon: HOME_CLEANING_ICONS.carpetCleaning,
    alt: 'Carpet Cleaning',
    color: 'purple',
    detailTitle: 'Carpet Cleaning Includes',
    includes: [
      'Inspection and vacuuming',
      'Steam and hot-water extraction',
      'Shampoo and low-moisture cleaning',
      'Stain treatment',
      'Deodorizing',
      'Deep-fiber and high-traffic cleaning',
      'Allergen and sanitation treatments',
      'Area, oriental, wool, and synthetic rug care',
      'Commercial and move-in/move-out carpet cleaning',
      'Protective treatments',
    ],
    notIncluded: [
      'Carpet repair or replacement',
      'Water-damage restoration',
      'Mold remediation',
      'Structural flooring repairs',
    ],
  },
  {
    id: 'window-gutter-cleaning',
    title: 'Window and Gutter Cleaning',
    description: 'Sparkling windows and clean gutters for a safer home.',
    icon: HOME_CLEANING_ICONS.windowAndGutterCleaning,
    alt: 'Window and Gutter Cleaning',
    color: 'orange',
    detailTitle: 'Window & Gutter Cleaning Includes',
    includes: [
      'Interior and exterior windows',
      'Screens, sills, frames, and tracks',
      'Hard-water stain removal',
      'Skylights and storm windows',
      'Residential and commercial window cleaning',
      'Gutter debris removal, inspection, downspout flushing, and unclogging',
      'Gutter-guard maintenance',
      'Fascia, soffit, eavestrough, and trim cleaning',
      'Drainage and safety inspections',
      'Seasonal gutter services',
    ],
    notIncluded: [
      'Gutter replacement or major repairs',
      'Roof repairs',
      'Exterior painting',
      'Structural maintenance',
      'Tree trimming',
    ],
  },
];
