import {
  CHILD_CARE_ICONS,
  CHILD_CARE_IMAGES,
} from './childcare/childCareServicesAssets';
import {
  SENIOR_PERSONAL_CARE_ICONS,
  SENIOR_PERSONAL_CARE_IMAGES,
} from './seniorpersonalcare/seniorPersonalCareAssets';
import {
  HOME_CLEANING_ICONS,
  HOME_CLEANING_IMAGES,
} from './homecleaning/homeCleaningServicesAssets';

export const CHILD_CARE_SERVICES = [
  {
    id: 'full-time-nannies',
    title: 'Full-time Nannies',
    description: 'Dedicated full-time care for your children with love and attention.',
    icon: CHILD_CARE_ICONS.fullTimeNannies,
    image: CHILD_CARE_IMAGES.fullTimeNannies,
    alt: 'Full-time Nannies',
    color: 'pink',
    accordionLabel: 'Full-time Nannies',
    detailTitle: 'What Full-time Nanny Care Includes',
    categories: [
      {
        title: 'Daily Care & Routines',
        icon: 'care',
        items: [
          'Supervision and safety of children always',
          'Feeding infants and children',
          'Preparing healthy meals and snacks',
          'Bathing, dressing, and grooming',
          'Diaper changing and toilet training',
          'Maintaining daily routines',
          'Putting children down for naps and bedtime',
        ],
      },
      {
        title: 'Education & Development',
        icon: 'education',
        items: [
          'Reading books and storytelling',
          'Assisting with homework',
          'Organizing educational and creative activities',
          'Supporting developmental milestones',
          'Encouraging social and emotional growth',
        ],
      },
      {
        title: 'Transportation & Activities',
        icon: 'transport',
        items: [
          'School drop-off and pick-up',
          'Transporting to activities, appointments and playdates',
          'Supervising outdoor play and recreation',
          'Accompanying children on outings',
        ],
      },
      {
        title: 'Household Support for Children',
        icon: 'household',
        items: [
          "Washing and folding children's laundry",
          'Organizing bedrooms and play areas',
          "Cleaning and sanitizing children's items (bottles, toys, highchairs, etc.)",
          'Maintaining wardrobes and supplies',
          'Meal prep and kitchen cleanup related to children',
        ],
      },
      {
        title: 'Health & Communication',
        icon: 'health',
        items: [
          'Administering medications as instructed by parents',
          'Monitoring health and reporting concerns',
          'Basic first aid and emergency response',
          'Daily updates on activities and behavior',
          'Coordinating schedules and routines',
        ],
      },
    ],
    notIncluded: [
      'Deep house cleaning',
      'Full family housekeeping',
      'Yard work',
      'Extensive cooking for all household members',
      'Personal errands unrelated to the children',
    ],
  },
  {
    id: 'part-time-nannies',
    title: 'Part-time Nannies',
    description: "Flexible part-time care that fits your family's schedule.",
    icon: CHILD_CARE_ICONS.partTimeNannies,
    image: CHILD_CARE_IMAGES.partTimeNannies,
    alt: 'Part-time Nannies',
    color: 'green',
    accordionLabel: 'Part-time Nannies',
    detailTitle: 'What Part-time Nanny Care Includes',
    categories: [
      {
        title: 'Daily Care & Routines',
        icon: 'care',
        items: [
          'Scheduled supervision',
          'Meals and snacks',
          'Hygiene',
          'Nap and routine support',
        ],
      },
      {
        title: 'Education & Development',
        icon: 'education',
        items: [
          'Reading, play, arts, and homework',
        ],
      },
      {
        title: 'Transportation & Activities',
        icon: 'transport',
        items: [
          'School/daycare pickup and drop-off if needed',
          'Playdates and outings',
        ],
      },
      {
        title: 'Household Support for Children',
        icon: 'household',
        items: [
          'Child-area tidying',
          'Child laundry',
        ],
      },
      {
        title: 'Health & Communication',
        icon: 'health',
        items: [
          'Basic first aid',
          'Parent updates',
          'Optional child-related errands, evening, or holiday care by agreement',
        ],
      },
    ],
    notIncluded: [
      'Deep cleaning',
      'Full housekeeping',
      'Extensive family cooking',
      'Yard maintenance',
      'Unrelated household-member care unless agreed',
    ],
  },
  {
    id: 'live-in-nannies',
    title: 'Live-in Nannies',
    description: 'Round-the-clock support and care right in your home.',
    icon: CHILD_CARE_ICONS.liveInNannies,
    image: CHILD_CARE_IMAGES.liveInNannies,
    alt: 'Live-in Nannies',
    color: 'purple',
    accordionLabel: 'Live-in Nannies',
    detailTitle: 'What Live-in Nanny Care Includes',
    categories: [
      {
        title: 'Daily Care & Routines',
        icon: 'care',
        items: [
          'Full-time supervision',
          'Morning and bedtime care',
          'Meals and hygiene',
        ],
      },
      {
        title: 'Education & Development',
        icon: 'education',
        items: [
          'Educational and developmental support',
        ],
      },
      {
        title: 'Transportation & Activities',
        icon: 'transport',
        items: [
          'School/activity transport',
        ],
      },
      {
        title: 'Household Support for Children',
        icon: 'household',
        items: [
          'Child laundry, bedrooms, and play areas',
          'Optional overnight support and parental-travel coverage',
          'Family meal prep and light child-related housekeeping by agreement',
        ],
      },
      {
        title: 'Health & Communication',
        icon: 'health',
        items: [
          'Health monitoring and basic first aid',
          'Daily parent updates',
        ],
      },
    ],
    familyProvides:
      'Family typically provides private room, bathroom access, meals during work periods, and utilities/accommodation.',
  },
  {
    id: 'babysitters',
    title: 'Babysitters',
    description: 'Safe and engaging care for your children when you need it.',
    icon: CHILD_CARE_ICONS.babysitters,
    image: CHILD_CARE_IMAGES.babysitters,
    alt: 'Babysitters',
    color: 'orange',
    accordionLabel: 'Babysitters',
    detailTitle: 'What Babysitting Includes',
    categories: [
      {
        title: 'Daily Care & Routines',
        icon: 'care',
        items: [
          'Short-term supervision and safety',
          'Feeding and bottle feeding',
          'Diapers, toilet, and hygiene',
          'Naps and bedtime',
        ],
      },
      {
        title: 'Education & Development',
        icon: 'education',
        items: [
          'Games, reading, arts, and educational play',
        ],
      },
      {
        title: 'Transportation & Activities',
        icon: 'transport',
        items: [
          'Evening, weekend, overnight, holiday, or emergency care if agreed',
        ],
      },
      {
        title: 'Household Support for Children',
        icon: 'household',
        items: [
          'Child-related cleanup',
        ],
      },
      {
        title: 'Health & Communication',
        icon: 'health',
        items: [
          'Parent updates',
        ],
      },
    ],
    notIncluded: [
      'Deep cleaning',
      'Full household housekeeping',
      'Family laundry',
      'Extensive family meal prep',
      'Household maintenance and yard work',
    ],
  },
  {
    id: 'in-home-support',
    title: 'In-home Support',
    description: 'Reliable assistance with daily living activities at home.',
    icon: CHILD_CARE_ICONS.inHomeSupport,
    image: CHILD_CARE_IMAGES.inHomeSupport,
    alt: 'In-home Support',
    color: 'blue',
    accordionLabel: 'In-home Support',
    detailTitle: 'In-home Support Details',
    summaryOnly: true,
  },
];

export const SENIOR_PERSONAL_CARE_SERVICES = [
  {
    id: 'companionship',
    title: 'Companionship',
    accordionLabel: 'Companionship',
    description: 'Friendly conversation, emotional support, and engaging activities at home.',
    icon: SENIOR_PERSONAL_CARE_ICONS.companionship,
    image: SENIOR_PERSONAL_CARE_IMAGES.companionship,
    alt: 'Companionship',
    color: 'pink',
    detailTitle: 'What Companionship Includes',
    includes: [
      'Friendly conversation and companionship',
      'Emotional support and encouragement',
      'Engaging in hobbies and activities',
      'Reading books, newspapers, and magazines',
      'Playing games and memory activities',
      'Accompanying on walks and outings',
      'Meal planning and grocery support',
      'Medication and hydration reminders',
      'Appointment reminders and schedule tracking',
      'Shopping and social or religious outings',
      'Light housekeeping support',
      'Family updates and respite support for caregivers',
      'Transportation and escort',
      'Wellness and home-safety observation',
    ],
    notIncluded: [
      'Medical treatments',
      'Injections',
      'Skilled nursing',
      'Physical therapy',
      'Heavy lifting or repairs',
    ],
  },
  {
    id: 'personal-care',
    title: 'Personal Care',
    accordionLabel: 'Personal Care',
    description: 'Respectful help with bathing, dressing, grooming, and daily living.',
    icon: SENIOR_PERSONAL_CARE_ICONS.personalCare,
    image: SENIOR_PERSONAL_CARE_IMAGES.personalCare,
    alt: 'Personal Care',
    color: 'green',
    detailTitle: 'What Personal Care Includes',
    includes: [
      'Bathing and showering',
      'Dressing and grooming',
      'Hygiene and oral care',
      'Toileting and incontinence support',
      'Mobility, transfers, and walking',
      'Meal and feeding assistance',
      'Medication and hydration reminders',
      'Daily routines',
      'Companionship',
      'Light household help',
      'Transportation and errands',
      'Wellness observation and family coordination',
    ],
    notIncluded: [
      'Diagnosis or treatment',
      'Skilled nursing',
      'Injections',
      'Physical therapy',
      'Heavy housekeeping or repairs',
    ],
  },
  {
    id: 'transportation',
    title: 'Transportation',
    accordionLabel: 'Transportation Support',
    description: 'Safe, accompanied rides to appointments, errands, and outings.',
    icon: SENIOR_PERSONAL_CARE_ICONS.transportation,
    image: SENIOR_PERSONAL_CARE_IMAGES.transportation,
    alt: 'Transportation',
    color: 'purple',
    detailTitle: 'Transportation Support Includes',
    includes: [
      'Doctor, hospital, dental, therapy, and specialist trips',
      'Pharmacy visits',
      'Grocery, banking, post office, and shopping',
      'Social, community, and religious activities',
      'Door-to-door help',
      'Vehicle entry and exit assistance',
      'Walker, wheelchair, and belongings support',
      'Accompanied trips, waiting, and return home',
      'Selected specialized non-emergency transport',
      'Family updates',
    ],
    notIncluded: [
      'Ambulance or emergency treatment',
      'Licensed nursing during transit',
    ],
  },
  {
    id: 'meal-preparation',
    title: 'Meal Preparation',
    accordionLabel: 'Meal Preparation Support',
    description: 'Nutritious, preference-based meals prepared in your kitchen.',
    icon: SENIOR_PERSONAL_CARE_ICONS.mealPreparation,
    image: SENIOR_PERSONAL_CARE_IMAGES.mealPreparation,
    alt: 'Meal Preparation',
    color: 'orange',
    detailTitle: 'Meal Preparation Support Includes',
    includes: [
      'Meal planning and customized menus',
      'Special-diet support',
      'Grocery lists, shopping, and storage',
      'Breakfast, lunch, dinner, snacks, and batch cooking',
      'Diabetic, low-sodium, heart-healthy, soft-food, allergy-aware, and cultural preferences',
      'Feeding assistance',
      'Kitchen cleanup',
      'Safe food handling',
      'Nutrition, hydration reminders, and family coordination',
    ],
    notIncluded: [
      'Clinical dietitian counseling',
      'Commercial or large-scale catering unless requested',
    ],
  },
  {
    id: 'light-housekeeping',
    title: 'Light Housekeeping',
    accordionLabel: 'Light Housekeeping',
    description: 'Everyday tidying to keep the home clean, safe, and comfortable.',
    icon: SENIOR_PERSONAL_CARE_ICONS.lightHousekeeping,
    image: SENIOR_PERSONAL_CARE_IMAGES.lightHousekeeping,
    alt: 'Light Housekeeping',
    color: 'blue',
    detailTitle: 'Light Housekeeping Includes',
    includes: [
      'Dusting',
      'Vacuuming',
      'Sweeping and mopping',
      'Counters and tables',
      'Trash and recycling',
      'Kitchen dishes, counters, sinks, and appliances',
      'Laundry, linens, and bed making',
      'Bathroom upkeep',
      'Organization and decluttering',
      'Hazard reduction',
      'Mail, plants, grocery unpacking, and light pet care',
    ],
    notIncluded: [
      'Deep cleaning',
      'Carpet shampooing',
      'Exterior windows',
      'Heavy lifting',
      'Repairs or yard work',
    ],
  },
];

export const HOME_CLEANING_SERVICES = [
  {
    id: 'maid-services',
    title: 'Maid Services',
    description:
      'Regular cleaning and upkeep to keep your home neat, organized, and stress-free.',
    icon: HOME_CLEANING_ICONS.maidServices,
    image: HOME_CLEANING_IMAGES.maidServices,
    alt: 'Maid Services',
    color: 'green',
    accordionLabel: 'Maid Services Includes',
    detailTitle: 'Maid Services Include',
    detailImage: HOME_CLEANING_IMAGES.inDepthBathroomCleaning,
    includes: [
      'General housekeeping',
      'Kitchen cleaning',
      'Bathroom cleaning',
      'Bedroom cleaning',
      'Laundry',
      'Home organization',
      'Deep cleaning',
      'Appliance cleaning',
      'Light household assistance',
      'Move-in/move-out cleaning',
      'Recurring options (daily/weekly/bi-weekly/monthly/one-time)',
    ],
    notIncluded: [
      'Heavy lifting',
      'Repairs',
      'Exterior windows',
      'Carpet installation/repair',
      'Landscaping or pest control',
    ],
  },
  {
    id: 'house-cleaning',
    title: 'House Cleaning',
    description:
      'Thorough cleaning of every corner for a healthier and more comfortable home.',
    icon: HOME_CLEANING_ICONS.houseCleaning,
    image: HOME_CLEANING_IMAGES.houseCleaning,
    alt: 'House Cleaning',
    color: 'blue',
    accordionLabel: 'House Cleaning Includes',
    detailTitle: 'House Cleaning Includes',
    detailImage: HOME_CLEANING_IMAGES.inDepthBathroomCleaning,
    includes: [
      'Living areas',
      'Common areas',
      'Kitchen',
      'Bathroom',
      'Bedrooms',
      'Laundry',
      'Linens',
      'Deep cleaning',
      'Closet organization',
      'Pantry organization',
      'Storage organization',
      'Move-in/move-out',
      'Post-renovation',
      'Seasonal cleaning',
      'Spring cleaning',
      'Vacation-rental turnover',
    ],
    notIncluded: [
      'Exterior windows',
      'Carpet steam cleaning',
      'Furniture moving',
      'Yard work',
      'Pest control or repairs',
    ],
  },
  {
    id: 'carpet-cleaning',
    title: 'Carpet Cleaning',
    description:
      'Deep carpet cleaning that removes dirt, stains, and allergens effectively.',
    icon: HOME_CLEANING_ICONS.carpetCleaning,
    image: HOME_CLEANING_IMAGES.carpetCleaning,
    alt: 'Carpet Cleaning',
    color: 'orange',
    accordionLabel: 'Carpet Cleaning Includes',
    detailTitle: 'Carpet Cleaning Includes',
    includes: [
      'Inspection',
      'Vacuuming',
      'Steam extraction',
      'Hot-water extraction',
      'Shampoo cleaning',
      'Low-moisture cleaning',
      'Stain treatment',
      'Deodorizing',
      'Deep-fiber cleaning',
      'High-traffic cleaning',
      'Allergen treatments',
      'Sanitation treatments',
      'Area rug care',
      'Oriental rug care',
      'Wool rug care',
      'Synthetic rug care',
      'Commercial carpet cleaning',
      'Move-in/move-out carpet cleaning',
      'Protective treatments',
    ],
    notIncluded: [
      'Carpet repair/replacement',
      'Water-damage restoration',
      'Mold remediation',
      'Structural flooring repairs',
    ],
  },
  {
    id: 'window-gutter-cleaning',
    title: 'Window & Gutter Cleaning',
    description:
      'Sparkling windows and clean gutters to protect your home and enhance its appearance.',
    icon: HOME_CLEANING_ICONS.windowAndGutterCleaning,
    image: HOME_CLEANING_IMAGES.windowGutterCleaning,
    alt: 'Window and Gutter Cleaning',
    color: 'purple',
    accordionLabel: 'Window & Gutter Cleaning Includes',
    detailTitle: 'Window & Gutter Cleaning Includes',
    includes: [
      'Interior windows',
      'Exterior windows',
      'Screens',
      'Sills',
      'Frames',
      'Tracks',
      'Hard-water stain removal',
      'Skylights',
      'Storm windows',
      'Residential window cleaning',
      'Commercial window cleaning',
      'Gutter debris removal',
      'Gutter inspection',
      'Downspout flushing',
      'Unclogging',
      'Gutter-guard maintenance',
      'Fascia cleaning',
      'Soffit cleaning',
      'Eavestrough cleaning',
      'Trim cleaning',
      'Drainage inspections',
      'Safety inspections',
      'Seasonal gutter services',
    ],
    notIncluded: [
      'Gutter replacement/major repairs',
      'Roof repairs',
      'Exterior painting',
      'Structural maintenance',
      'Tree trimming',
    ],
  },
];
