export const SENIOR_PERSONAL_CARE_ICONS = {
  companionship: '/seniorpersonalcare/companionship.svg',
  personalCare: '/seniorpersonalcare/personalcare.svg',
  transportation: '/seniorpersonalcare/transportation.svg',
  mealPreparation: '/seniorpersonalcare/mealpreparation.svg',
  lightHousekeeping: '/seniorpersonalcare/lighthousekeeping.svg',
};

export const SENIOR_PERSONAL_CARE_IMAGES = {
  hero: '/herosenior.webp',
  comfort: '/comfort.webp',
  companionship: '/senior/companionship.webp',
  personalCare: '/senior/personal_care.webp',
  transportation: '/senior/transportation.webp',
  mealPreparation: '/senior/meal_preparation.webp',
  lightHousekeeping: '/senior/light_housekeeping.webp',
};

export const SENIOR_CARE_COLORS = {
  pink: {
    header: 'bg-[#c72a7a]',
    headerBg: 'bg-[#fde8ef]',
    headerBorder: 'border-[#f0b8cc]',
    accentText: 'text-[#c72a7a]',
    iconBg: 'bg-[#c72a7a]',
    border: 'border-[#c72a7a]',
    ring: 'ring-[#c72a7a]/25',
    panel: 'bg-[#fdf2f6]',
    panelBorder: 'border-[#e8a0be]',
    bullet: 'text-[#c72a7a]',
  },
  green: {
    header: 'bg-[#4caf50]',
    headerBg: 'bg-[#edf7ea]',
    headerBorder: 'border-[#b8ddb0]',
    accentText: 'text-[#4caf50]',
    iconBg: 'bg-[#4caf50]',
    border: 'border-[#4caf50]',
    ring: 'ring-[#4caf50]/25',
    panel: 'bg-[#f3faf3]',
    panelBorder: 'border-[#a8d49e]',
    bullet: 'text-[#4caf50]',
  },
  purple: {
    header: 'bg-[#9c27b0]',
    headerBg: 'bg-[#f3ecfa]',
    headerBorder: 'border-[#cdb8e8]',
    accentText: 'text-[#9c27b0]',
    iconBg: 'bg-[#9c27b0]',
    border: 'border-[#9c27b0]',
    ring: 'ring-[#9c27b0]/25',
    panel: 'bg-[#f8f1fa]',
    panelBorder: 'border-[#c0a8e0]',
    bullet: 'text-[#9c27b0]',
  },
  orange: {
    header: 'bg-[#ff9800]',
    headerBg: 'bg-[#fff4e8]',
    headerBorder: 'border-[#ffd4a8]',
    accentText: 'text-[#ff9800]',
    iconBg: 'bg-[#ff9800]',
    border: 'border-[#ff9800]',
    ring: 'ring-[#ff9800]/25',
    panel: 'bg-[#fff8ee]',
    panelBorder: 'border-[#ffc888]',
    bullet: 'text-[#ff9800]',
  },
  blue: {
    header: 'bg-[#2196f3]',
    headerBg: 'bg-[#e8f5fd]',
    headerBorder: 'border-[#a8d4f0]',
    accentText: 'text-[#2196f3]',
    iconBg: 'bg-[#2196f3]',
    border: 'border-[#2196f3]',
    ring: 'ring-[#2196f3]/25',
    panel: 'bg-[#f1f8fe]',
    panelBorder: 'border-[#98c8ec]',
    bullet: 'text-[#2196f3]',
  },
};

export { SERVICE_PHOTO_RADIUS } from '../childcare/childCareServicesAssets';
